FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y nginx

RUN chown -R www-data:www-data /var/lib/nginx
RUN rm -rf /var/lib/apt/lists/*


EXPOSE 80

ADD conf/nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

CMD ["nginx", "-g", "daemon off;"]
