FROM ubuntu:16.04

RUN apt-get update && \
    apt-get -y install \
    apache2 \
    php7.0 \
    libapache2-mod-php7.0 \
    php7.0-pgsql
   
RUN rm -rf /var/lib/apt/lists/*

ADD conf/index.php /var/www/html/index.php
ADD conf/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod remoteip
WORKDIR /var/www/html
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE=/var/run/apache2.pid
ENV APACHE_RUN_DIR=/var/run/apache2
ENV APACHE_LOCK_DIR=/var/lock/apache2

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]

